sudo: false
language: ruby
script: 'bundle exec rake'
rvm:
  - 2.2.5
before_install:
  - gem install bundler -v 1.12.5
notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never

matrix:
  include:
    - rvm: 2.7.2
      env: MONGOID_VERSION=4
    - rvm: 2.7.2
      env: MONGOID_VERSION=5
    - rvm: 2.7.2
      env: MONGOID_VERSION=6
    - rvm: 2.7.2
      env: MONGOID_VERSION=7
